/* eslint-disable prettier/prettier */
import { StyleSheet } from 'react-native';
import { MDBLUE, WHITE, GRAY, GRAY_SHADE, BLACK } from '../../shared/common-styles/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: WHITE,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  filterContainer: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  filterScrollContainer: {
    paddingHorizontal: 4,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#F5F5F5',
    borderRadius: 20,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  selectedFilterChip: {
    backgroundColor: MDBLUE,
    borderColor: MDBLUE,
  },
  filterChipText: {
    fontSize: 14,
    color: GRAY,
    fontFamily: 'Poppins-Medium',
  },
  selectedFilterChipText: {
    color: WHITE,
  },
  userCategoryContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    marginVertical: 8,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryTextContainer: {
    flex: 0.7, // Takes 70% of the width
  },
  userCategoryText: {
    fontSize: 14,
    color: GRAY,
  },
  userCategoryValue: {
    color: MDBLUE,
  },
  smallToggleButton: {
    flex: 0.3, // Takes 30% of the width
    backgroundColor: MDBLUE,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 15,
    alignItems: 'center',
    marginLeft: 10,
    minHeight: 32,
    justifyContent: 'center',
  },
  smallToggleButtonText: {
    fontSize: 12,
    color: WHITE,
    fontFamily: 'Poppins-SemiBold',
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: GRAY,
    fontFamily: 'Poppins-Regular',
  },
  listContainer: {
    paddingVertical: 8,
    flexGrow: 1,
  },
  offerCard: {
    backgroundColor: '#8E44AD', // Deep purple base
    borderRadius: 20,
    marginVertical: 12,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
    minHeight: 180,
    position: 'relative',
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#9B59B6', // Lighter purple overlay
    opacity: 0.7,
  },
  decorativeElements: {
    position: 'absolute',
    top: -30,
    left: -30,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    transform: [{ rotate: '45deg' }],
  },
  decorativeElements2: {
    position: 'absolute',
    bottom: -40,
    right: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  curvedBorder: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 80,
    height: 80,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderBottomRightRadius: 80,
  },
  offerBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  offerBadgeText: {
    color: WHITE,
    fontSize: 12,
    fontFamily: 'Poppins-SemiBold',
    fontWeight: '600',
  },
  offerContent: {
    
    flexDirection: 'row',
    flex: 1,
    zIndex: 2,
  },
  offerImageContainer: {
     
    width: '40%',
    height: '100%',
    minHeight: 180,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    overflow: 'hidden',
    backgroundColor: 'rgba(139, 69, 173, 0.3)', // Purplish background to match
  },
  offerImage: {
    width: '100%',
    height: '100%',
  },
  offerRightContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 16,
    justifyContent: 'space-between',
  },
  offerHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginBottom: 8,
    zIndex: 2,
  },
  offerTextContainer: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  offerFooter: {
    paddingTop: 12,
    zIndex: 2,
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  placeholderText: {
    fontSize: 10,
    color: WHITE,
    fontFamily: 'Poppins-Regular',
  },
  offerDetails: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  offerTitle: {
    fontSize: 18,
    color: WHITE,
    marginBottom: 6,
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    lineHeight: 24,
  },
  offerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 8,
    fontFamily: 'Poppins-Medium',
    lineHeight: 20,
  },
  offerType: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 4,
    fontFamily: 'Poppins-Regular',
  },
  productNames: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    lineHeight: 16,
    fontFamily: 'Poppins-Regular',
  },
  viewOfferButton: {
    backgroundColor: WHITE,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    alignSelf: 'flex-start',
  },
  viewOfferButtonText: {
    color: '#8E44AD',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
    fontWeight: '600',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    color: GRAY,
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    paddingHorizontal: 20,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '100%',
    height: '100%',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1000,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  modalCloseButtonText: {
    color: WHITE,
    fontSize: 28,
    fontWeight: 'bold',
    lineHeight: 28,
  },
  modalImageContainer: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 100,
  },
  modalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 100,
  },
  modalImageWrapper: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalImage: {
    width: '90%',
    height: 400,
    maxWidth: 500,
  },
  modalOfferNameContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingVertical: 24,
    paddingHorizontal: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalOfferName: {
    fontSize: 20,
    color: WHITE,
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
    lineHeight: 28,
  },
});