import { StyleSheet } from 'react-native';
import { MDBLUE, WHITE, GRAY, BLACK, LIGHTGREY } from '../../shared/common-styles/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  content: {
    flex: 1,
  },
  messagesContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  messageContainer: {
    marginVertical: 4,
  },
  userMessage: {
    alignItems: 'flex-end',
  },
  supportMessage: {
    alignItems: 'flex-start',
  },
  messageBubble: {
    maxWidth: '80%',
    padding: 12,
    borderRadius: 18,
  },
  userBubble: {
    backgroundColor: MDBLUE,
    borderBottomRightRadius: 4,
  },
  supportBubble: {
    backgroundColor: WHITE,
    borderBottomLeftRadius: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
  },
  userText: {
    color: WHITE,
  },
  supportText: {
    color: BLACK,
  },
  messageTime: {
    fontSize: 11,
    alignSelf: 'flex-end',
  },
  userTime: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  supportTime: {
    color: GRAY,
  },
  inputContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: WHITE,
    alignItems: 'flex-end',
    borderTopWidth: 1,
    borderTopColor: LIGHTGREY,
  },
  messageInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: LIGHTGREY,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: BLACK,
    maxHeight: 100,
    marginRight: 12,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: MDBLUE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  attachmentButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: GRAY,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  attachmentPreviewContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: WHITE,
  },
  attachmentPreview: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 8,
    backgroundColor: LIGHTGREY,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  attachmentImage: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  attachmentDocument: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  documentText: {
    fontSize: 8,
    textAlign: 'center',
    color: MDBLUE,
    fontFamily: 'Poppins-Regular',
  },
  removeAttachment: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FF4444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeAttachmentText: {
    color: WHITE,
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
  },
  messageImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
    marginBottom: 8,
  },
  messageDocument: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 8,
    marginBottom: 8,
    maxWidth: 250,
  },
  documentIcon: {
    width: 32,
    height: 32,
    backgroundColor: MDBLUE,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  documentIconText: {
    color: WHITE,
    fontSize: 10,
    fontFamily: 'Poppins-Bold',
  },
  documentInfo: {
    flex: 1,
  },
  documentName: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    color: BLACK,
    marginBottom: 2,
  },
  documentType: {
    fontSize: 10,
    fontFamily: 'Poppins-Regular',
    color: GRAY,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
});