/* eslint-disable prettier/prettier */
import { StyleSheet } from 'react-native';
import { WHITE, BLACK, GRAY, MDBLUE } from '../../shared/common-styles/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContentContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: MDBLUE,
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 50, // Account for status bar
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    color: WHITE,
    marginHorizontal: 16,
  },
  submitButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  submitButtonText: {
    color: WHITE,
    fontSize: 14,
  },
  content: {
    flex: 1,
  },
  section: {
    backgroundColor: WHITE,
    marginHorizontal: 12,
    marginVertical: 8,
    borderRadius: 12,
    padding: 16,
    
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 16,
    color: BLACK,
    marginBottom: 12,
  },
  descriptionInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: BLACK,
    minHeight: 120,
    textAlignVertical: 'top',
  },
  characterCount: {
    fontSize: 12,
    color: GRAY,
    textAlign: 'right',
    marginTop: 8,
  },
  imageSection: {
    borderWidth: 2,
    borderColor: '#E8F4FD',
    borderStyle: 'dashed',
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
    backgroundColor: '#F8FCFF',
  },
  imageSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  imageSectionTitle: {
    fontSize: 16,
    color: MDBLUE,
    marginLeft: 8,
  },
  imageSectionSubtitle: {
    fontSize: 12,
    color: GRAY,
    textAlign: 'center',
  },
  selectedImageContainer: {
    marginTop: 16,
    position: 'relative',
  },
  selectedImage: {
    width: '100%',
    height: 200,
    borderRadius: 8,
  },
  removeImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeImageText: {
    color: WHITE,
    fontSize: 20,
    fontWeight: 'bold',
  },
  tagSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  tagSectionTitle: {
    fontSize: 16,
    color: BLACK,
    marginLeft: 8,
  },
  tagsInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: BLACK,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  tagsHelperText: {
    fontSize: 12,
    color: GRAY,
    marginTop: 8,
  },
  bottomSpacing: {
    height: 40,
  },
  bottomButtonContainer: {
    backgroundColor: WHITE,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  bottomSubmitButton: {
    backgroundColor: MDBLUE,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomSubmitButtonText: {
    color: WHITE,
    fontSize: 16,
  },
  // New styles for the step-by-step flow
  stepContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  stepIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FFE8E8',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  stepTitle: {
    paddingTop: 4,
    fontSize: 20,
    color: BLACK,
    textAlign: 'center',
    marginBottom: 10,
  },
  stepSubtitle: {
    fontSize: 14,
    color: GRAY,
    textAlign: 'center',
    marginBottom: 30,
  },
  cropGrid: {
    paddingHorizontal: 20,
  },
  cropItem: {
    width: '30%',
    marginHorizontal: '1.66%',
    marginVertical: 8,
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 10,
    alignItems: 'center',
    position: 'relative',
  },
  cropItemSelected: {
    backgroundColor: '#E8F4FD',
    borderWidth: 2,
    borderColor: MDBLUE,
  },
  selectedIndicator: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: MDBLUE,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  checkIcon: {
    color: WHITE,
    fontSize: 12,
    fontWeight: 'bold',
  },
  cropImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 8,
  },
  cropName: {
    fontSize: 12,
    color: BLACK,
    textAlign: 'center',
  },
  expandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: MDBLUE,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 15,
  },
  expandButtonText: {
    color: WHITE,
    fontSize: 14,
    marginLeft: 5,
  },
  progressBar: {
    height: 4,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 20,
    marginBottom: 20,
  },
  progressFill: {
    height: '100%',
    backgroundColor: MDBLUE,
  },
  navigationButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: WHITE,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  navButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    minWidth: 100,
    alignItems: 'center',
  },
  navButtonPrimary: {
    backgroundColor: MDBLUE,
  },
  navButtonSecondary: {
    backgroundColor: GRAY,
  },
  navButtonText: {
    paddingTop: 4,
    color: WHITE,
    fontSize: 16,
  },
  recordButton: {
    backgroundColor: '#F0F0F0',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: 'center',
    marginTop: 10,
  },
  recordButtonText: {
    color: GRAY,
    fontSize: 14,
  },
  // Category selection styles
  categorySection: {
    width: '100%',
    paddingHorizontal: 20,
  },
  categoryOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: WHITE,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  categoryOptionSelected: {
    borderColor: MDBLUE,
    backgroundColor: '#E8F4FD',
  },
  categoryIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  categoryIcon: {
    fontSize: 24,
  },
  categoryContent: {
    flex: 1,
  },
  categoryTitle: {
    fontSize: 16,
    color: BLACK,
    marginBottom: 4,
  },
  categoryDescription: {
    fontSize: 12,
    color: GRAY,
  },
  selectedIndicatorCategory: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: MDBLUE,
    justifyContent: 'center',
    alignItems: 'center',
  },
});